package com.zdsoft.edu.dto.log;

import java.util.Date;

public class OperateLogDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_operate_log_1.logtype
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	private Short logtype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_operate_log_1.userid
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	private Long userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_operate_log_1.createtime
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_operate_log_1.logcontent
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	private String logcontent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_operate_log_1.ipaddr
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	private String ipaddr;
	
	private String tableName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_operate_log_1.logtype
	 * @return  the value of t_operate_log_1.logtype
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	public Short getLogtype() {
		return logtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_operate_log_1.logtype
	 * @param logtype  the value for t_operate_log_1.logtype
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	public void setLogtype(Short logtype) {
		this.logtype = logtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_operate_log_1.userid
	 * @return  the value of t_operate_log_1.userid
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_operate_log_1.userid
	 * @param userid  the value for t_operate_log_1.userid
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_operate_log_1.createtime
	 * @return  the value of t_operate_log_1.createtime
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_operate_log_1.createtime
	 * @param createtime  the value for t_operate_log_1.createtime
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_operate_log_1.logcontent
	 * @return  the value of t_operate_log_1.logcontent
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	public String getLogcontent() {
		return logcontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_operate_log_1.logcontent
	 * @param logcontent  the value for t_operate_log_1.logcontent
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	public void setLogcontent(String logcontent) {
		this.logcontent = logcontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_operate_log_1.ipaddr
	 * @return  the value of t_operate_log_1.ipaddr
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	public String getIpaddr() {
		return ipaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_operate_log_1.ipaddr
	 * @param ipaddr  the value for t_operate_log_1.ipaddr
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	public void setIpaddr(String ipaddr) {
		this.ipaddr = ipaddr;
	}

	public String getTableName() {
		return tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}
	
	
}