package com.zdsoft.edu.dao.order;

import com.zdsoft.edu.dto.order.OrderDto;

public interface OrderDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_edu_order
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	int deleteByPrimaryKey(Long orderid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_edu_order
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	int insert(OrderDto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_edu_order
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	int insertSelective(OrderDto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_edu_order
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	OrderDto selectByPrimaryKey(Long orderid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_edu_order
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	int updateByPrimaryKeySelective(OrderDto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_edu_order
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	int updateByPrimaryKey(OrderDto record);
}