package com.zdsoft.edu.dao.log;

import com.zdsoft.edu.dto.log.OperateLogDto;

public interface OperateLogDao {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_operate_log_1
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	int insert(OperateLogDto record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_operate_log_1
	 * @mbg.generated  Sun May 21 09:56:42 GMT+08:00 2017
	 */
	int insertSelective(OperateLogDto record);
}