package com.zdsoft.edu.dto.order;

import java.math.BigDecimal;
import java.util.Date;

public class OrderDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_order.orderid
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private Long orderid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_order.userid
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private Long userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_order.orderamount
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private BigDecimal orderamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_order.ordertime
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private Date ordertime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_order.paymenttype
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private Byte paymenttype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_order.status
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_order.receivemobile
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private String receivemobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_order.addressdesc
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private String addressdesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_order.receivename
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private String receivename;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_order.orderid
	 * @return  the value of t_edu_order.orderid
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public Long getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_order.orderid
	 * @param orderid  the value for t_edu_order.orderid
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setOrderid(Long orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_order.userid
	 * @return  the value of t_edu_order.userid
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public Long getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_order.userid
	 * @param userid  the value for t_edu_order.userid
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setUserid(Long userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_order.orderamount
	 * @return  the value of t_edu_order.orderamount
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public BigDecimal getOrderamount() {
		return orderamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_order.orderamount
	 * @param orderamount  the value for t_edu_order.orderamount
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setOrderamount(BigDecimal orderamount) {
		this.orderamount = orderamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_order.ordertime
	 * @return  the value of t_edu_order.ordertime
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public Date getOrdertime() {
		return ordertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_order.ordertime
	 * @param ordertime  the value for t_edu_order.ordertime
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setOrdertime(Date ordertime) {
		this.ordertime = ordertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_order.paymenttype
	 * @return  the value of t_edu_order.paymenttype
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public Byte getPaymenttype() {
		return paymenttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_order.paymenttype
	 * @param paymenttype  the value for t_edu_order.paymenttype
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setPaymenttype(Byte paymenttype) {
		this.paymenttype = paymenttype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_order.status
	 * @return  the value of t_edu_order.status
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_order.status
	 * @param status  the value for t_edu_order.status
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_order.receivemobile
	 * @return  the value of t_edu_order.receivemobile
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public String getReceivemobile() {
		return receivemobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_order.receivemobile
	 * @param receivemobile  the value for t_edu_order.receivemobile
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setReceivemobile(String receivemobile) {
		this.receivemobile = receivemobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_order.addressdesc
	 * @return  the value of t_edu_order.addressdesc
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public String getAddressdesc() {
		return addressdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_order.addressdesc
	 * @param addressdesc  the value for t_edu_order.addressdesc
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setAddressdesc(String addressdesc) {
		this.addressdesc = addressdesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_order.receivename
	 * @return  the value of t_edu_order.receivename
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public String getReceivename() {
		return receivename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_order.receivename
	 * @param receivename  the value for t_edu_order.receivename
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setReceivename(String receivename) {
		this.receivename = receivename;
	}
}