package com.zdsoft.edu.dto.course;

import java.math.BigDecimal;
import java.util.Date;

public class CourseDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_course.courseid
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private Long courseid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_course.coursename
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private String coursename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_course.createuser
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private Long createuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_course.coursedesc
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private String coursedesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_course.isfree
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private Byte isfree;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_course.courseamount
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private BigDecimal courseamount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_course.coursetype
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private Short coursetype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_course.courselogo
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private String courselogo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_course.createtime
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_course.updatetime
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_edu_course.viewcount
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	private Long viewcount;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_course.courseid
	 * @return  the value of t_edu_course.courseid
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public Long getCourseid() {
		return courseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_course.courseid
	 * @param courseid  the value for t_edu_course.courseid
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setCourseid(Long courseid) {
		this.courseid = courseid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_course.coursename
	 * @return  the value of t_edu_course.coursename
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public String getCoursename() {
		return coursename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_course.coursename
	 * @param coursename  the value for t_edu_course.coursename
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setCoursename(String coursename) {
		this.coursename = coursename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_course.createuser
	 * @return  the value of t_edu_course.createuser
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public Long getCreateuser() {
		return createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_course.createuser
	 * @param createuser  the value for t_edu_course.createuser
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setCreateuser(Long createuser) {
		this.createuser = createuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_course.coursedesc
	 * @return  the value of t_edu_course.coursedesc
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public String getCoursedesc() {
		return coursedesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_course.coursedesc
	 * @param coursedesc  the value for t_edu_course.coursedesc
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setCoursedesc(String coursedesc) {
		this.coursedesc = coursedesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_course.isfree
	 * @return  the value of t_edu_course.isfree
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public Byte getIsfree() {
		return isfree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_course.isfree
	 * @param isfree  the value for t_edu_course.isfree
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setIsfree(Byte isfree) {
		this.isfree = isfree;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_course.courseamount
	 * @return  the value of t_edu_course.courseamount
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public BigDecimal getCourseamount() {
		return courseamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_course.courseamount
	 * @param courseamount  the value for t_edu_course.courseamount
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setCourseamount(BigDecimal courseamount) {
		this.courseamount = courseamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_course.coursetype
	 * @return  the value of t_edu_course.coursetype
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public Short getCoursetype() {
		return coursetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_course.coursetype
	 * @param coursetype  the value for t_edu_course.coursetype
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setCoursetype(Short coursetype) {
		this.coursetype = coursetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_course.courselogo
	 * @return  the value of t_edu_course.courselogo
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public String getCourselogo() {
		return courselogo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_course.courselogo
	 * @param courselogo  the value for t_edu_course.courselogo
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setCourselogo(String courselogo) {
		this.courselogo = courselogo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_course.createtime
	 * @return  the value of t_edu_course.createtime
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_course.createtime
	 * @param createtime  the value for t_edu_course.createtime
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_course.updatetime
	 * @return  the value of t_edu_course.updatetime
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_course.updatetime
	 * @param updatetime  the value for t_edu_course.updatetime
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_edu_course.viewcount
	 * @return  the value of t_edu_course.viewcount
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public Long getViewcount() {
		return viewcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_edu_course.viewcount
	 * @param viewcount  the value for t_edu_course.viewcount
	 * @mbg.generated  Wed May 10 00:21:22 GMT+08:00 2017
	 */
	public void setViewcount(Long viewcount) {
		this.viewcount = viewcount;
	}
}